spring
   profiles:
      active:
      - dev
---
spring
   profiles: dev
   application:
       name: springcloud-coinfig-dev
---
spring
   profiles: test
   application:
       name: springcloud-coinfig-test

        


