spring:
   profiles:
      active:
      - dev
---
server:
   port: 7101
spring:
   profiles: dev
   application:
       name: springcloud-coinfig-eureka
eureka:
  instance:
    hostname: my.config.con
  client:
    register-with-eureka: false  #注册自己
    fetch-registry: false    #自检（维护自己）
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 7102
spring:
  profiles: test
  application:
    name: springcloud-coinfig-eureka
eureka:
  instance:
    hostname: my.config.con
  client:
    register-with-eureka: false  #注册自己
    fetch-registry: false    #自检（维护自己）
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

        


