spring:
   profiles:
      active:
      - dev
---
server:
   port: 8001
spring:
   profiles: dev
   application:
       name: springcloud-coinfig-dept
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.1.66:3366/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: 123456
mybatis:
    mapper-locations: classpath:mapper/*.xml
logging:
    level:
       com.my.springcloud.dept: debug

eureka:
  instance:
    hostname: my.config.con
  client:
    service-url:
      defaultZone: http://my.config.con:7101/eureka/
---
server:
  port: 8002
spring:
  profiles: test
  application:
    name: springcloud-coinfig-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.66:3366/spring_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
    mapper-locations: classpath:mapper/*.xml
logging:
    level:
      com.my.springcloud.dept: debug

eureka:
  client:
    register-with-eureka: false  #注册自己
    fetch-registry: false    #自检（维护自己）
    service-url:
      defaultZone: http://my.config.con:7102/eureka/

        


