spring:
   profiles:
      active:
      - dev
---
server:
   port: 7101
spring:
   profiles: dev
   application:
       name: springcloud-coinfig-dev
eureka:
   client:
     server-url:
        defaultZone: http://http://my.config.con:5001
---
server:
   port: 7101
spring:
   profiles: test
   application:
       name: springcloud-coinfig-test
eureka:
   client:
     server-url:
        defaultZone: http://http://my.config.con:5001

        


